//
//  LlamaServer.swift
//  Sidekick
//
//  Created by Bean John on 10/9/24.
//

import EventSource
import Foundation
import FSKit_macOS
import OSLog
import SimilaritySearchKit

/// The inference server where LLM inference happens
public actor LlamaServer {
    
    // MARK: - Core Configuration
    
    static let logger: Logger = .init(
        subsystem: Bundle.main.bundleIdentifier!,
        category: String(describing: LlamaServer.self)
    )
    
    var modelType: ModelType
    var systemPrompt: String
    
    // MARK: - Connection Details
    
    var host: String = "127.0.0.1"
    var port: String
    var scheme: String = "http"
    
    // MARK: - Process State
    
    var isStartingServer: Bool = false
    var monitor: Process = Process()
    var process: Process = Process()
    /// Timer responsible for writing heartbeat bytes to the watchdog.
    /// Held so it can be cancelled on shutdown — otherwise it keeps firing
    /// (and leaks the pipe) after the monitor process has been terminated.
    var heartbeatTimer: DispatchSourceTimer?
    /// Backing pipe for the watchdog heartbeat. Retained for the lifetime of
    /// the monitor process so the file descriptor can be closed deterministically.
    var heartbeatPipe: Pipe?
    
    /// Tracks request-scoped streaming resources so multiple in-flight calls can run concurrently.
    var activeRequests: [UUID: ActiveRequestContext] = [:]
    var pendingCancellationForAllRequests: Bool = false
    
    // MARK: - Initialization
    
    init(
        modelType: ModelType,
        systemPrompt: String = InferenceSettings.systemPrompt
    ) {
        self.modelType = modelType
        self.systemPrompt = systemPrompt
        self.port = {
            switch modelType {
                case .regular:
                    return "4579"
                case .worker:
                    return "9830"
            }
        }()
    }

    /// Fixed context length used when this server is hosting the
    /// worker model. The worker exists to handle short, well-bounded
    /// tasks (memory extraction, prompt suggestions, canvas ops);
    /// growing its context to match the main model wastes a lot of
    /// KV-cache memory for no benefit, so it's hard-pinned here and
    /// intentionally ignores per-model overrides and the
    /// device-scaled ``InferenceSettings/contextLength`` default.
    static let workerContextLength: Int = 4096
    static let localParallelSlots: Int = 2

    /// Context length to use when launching `llama-server` for this
    /// model. Worker servers are pinned to ``workerContextLength``;
    /// regular servers prefer the per-model override saved by
    /// ``ModelLoadConfigSheet`` and fall back to the legacy global
    /// default for models that haven't been configured yet.
    var contextLength: Int {
        if self.modelType == .worker {
            return Self.workerContextLength
        }
        if let url = self.modelUrl,
           let config = ModelManager.loadConfig(for: url),
           let perModel = config.contextLength {
            return perModel
        }
        return InferenceSettings.contextLength
    }

    var parallelSlots: Int {
        return Self.localParallelSlots
    }

    var totalContextLength: Int {
        return self.contextLength * self.parallelSlots
    }
    
    // MARK: - Model Metadata
    
    var modelUrl: URL? {
        switch self.modelType {
            case .regular:
                return Settings.modelUrl
            case .worker:
                return InferenceSettings.workerModelUrl
        }
    }
    
    var modelName: String {
        return self.modelUrl?.deletingPathExtension().lastPathComponent ?? "Unknown Model"
    }
    
    func modelHasVision(
        usingRemoteModel: Bool
    ) -> Bool {
        return Self.modelHasVision(
            type: self.modelType,
            usingRemoteModel: usingRemoteModel
        )
    }
    
    static func modelHasVision(
        type: ModelType,
        usingRemoteModel: Bool
    ) -> Bool {
        // Return false if using non-regular model
        if type != .regular {
            return false
        }
        // Using local model and has vision enabled, and has projector
        if !usingRemoteModel && InferenceSettings.localModelHasVision {
            return true
        }
        print("\(InferenceSettings.serverModelName) vision: \(InferenceSettings.serverModelHasVision)")
        // Else, get toggle value
        return InferenceSettings.serverModelHasVision
    }
    
    // MARK: - Configuration Mutations
    
    public func setSystemPrompt(_ systemPrompt: String) {
        self.systemPrompt = systemPrompt
    }
    
    /// Function executed when output finishes
    /// - Parameter text: The output generated by the LLM
    public func onFinish(text: String) {}
    
}

extension LlamaServer {
    
    /// Container for request-local streaming state that must be cancelled independently.
    final class ActiveRequestContext {
        
        let id: UUID
        let eventSource: EventSource
        let dataTask: EventSource.DataTask
        let session: URLSession
        var isCancelled: Bool
        
        init(
            id: UUID,
            eventSource: EventSource,
            dataTask: EventSource.DataTask,
            session: URLSession,
            isCancelled: Bool = false
        ) {
            self.id = id
            self.eventSource = eventSource
            self.dataTask = dataTask
            self.session = session
            self.isCancelled = isCancelled
        }
        
        func cancel() {
            guard !isCancelled else { return }
            isCancelled = true
            dataTask.cancel(urlSession: session)
        }
        
    }
    
}
